############## PACS ##############
PACS0: 
  lr: 5e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
PACS1: 
  lr: 3e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
PACS2: 
  lr: 3e-5
  resnet_dropout: 0.0
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
PACS3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
############## VLCS ##############
VLCS0: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
VLCS1: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
VLCS2: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
VLCS3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
###### OfficeHome ######
OfficeHome0: 
  lr: 3e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
OfficeHome1: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
OfficeHome2: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
OfficeHome3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "label"
############## TerraIncognita ##############
TerraIncognita0: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
TerraIncognita1: 
  lr: 5e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
TerraIncognita2: 
  lr: 5e-5
  resnet_dropout: 0.0
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
TerraIncognita3: 
  lr: 5e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
############## DomainNet ##############
DomainNet0: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
DomainNet1: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
DomainNet2: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
DomainNet3: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"
DomainNet4: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "label"
DomainNet5: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "label"