############## PACS ##############
PACS0: 
  lr: 5e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
PACS1: 
  lr: 3e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
PACS2: 
  lr: 3e-5
  resnet_dropout: 0.0
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
PACS3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
############## VLCS ##############
VLCS0: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
VLCS1: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
VLCS2: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
VLCS3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
############## OfficeHome ##############
OfficeHome0: 
  lr: 3e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
OfficeHome1: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
OfficeHome2: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
OfficeHome3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
############## TerraIncognita ##############
TerraIncognita0: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
TerraIncognita1: 
  lr: 5e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
TerraIncognita2: 
  lr: 5e-5
  resnet_dropout: 0.0
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
TerraIncognita3: 
  lr: 5e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
############## DomainNet ##############
DomainNet0: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
DomainNet1: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
DomainNet2: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
DomainNet3: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
DomainNet4: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1
DomainNet5: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wide"
  auto_da: "ta"
  da_mode: "online"
  resnet18: False
  num_ops: 1
  num_samples: 1