############## PACS ##############
PACS0: 
  lr: 5e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
PACS1: 
  lr: 3e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
PACS2: 
  lr: 3e-5
  resnet_dropout: 0.0
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "domain"
PACS3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
############## VLCS ##############
VLCS0: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
VLCS1: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
VLCS2: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
VLCS3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
###### OfficeHome #######
OfficeHome0: 
  lr: 3e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
OfficeHome1: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
OfficeHome2: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
OfficeHome3: 
  lr: 1e-5
  resnet_dropout: 0.5
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.8
  reward: "domain"
############## TerraIncognita ##############
TerraIncognita0: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "domain"
TerraIncognita1: 
  lr: 5e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
TerraIncognita2: 
  lr: 5e-5
  resnet_dropout: 0.0
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "domain"
TerraIncognita3: 
  lr: 5e-5
  resnet_dropout: 0.5
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
############## DomainNet ##############
DomainNet0: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
DomainNet1: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-04
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
DomainNet2: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.5
  reward: "domain"
DomainNet3: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
DomainNet4: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"
DomainNet5: 
  lr: 3e-5
  resnet_dropout: 0.1
  weight_decay: 1e-06
  data_augmentation: "aug"
  tf_range: "wider"
  auto_da: "uniform"
  da_mode: "append"
  resnet18: False
  num_ops: 1
  num_samples: 1
  alpha: 0.2
  reward: "domain"